### ISSUE TITLE
Exception due to undefined var/method

### ISSUE THREAD

**Issue by sihil** [scottrobertson/monzo-to-qif#3]
Thanks for creating this - I've just got my Monzo card and this will totally make keeping YNAB in sync a lot easier. 🎉 😄 

I can't get HEAD of master to run, instead I get the following exception:
```
monzo-to-qif git:(master)$ ruby monzo-to-qif.rb generate --access_token=$MONZO --since=2016-10-10 --folder=/Users/shildrew/test/monzo --trace
[1/5] Exporting [2017-06-09T14:34:29+00:00] tx_00009LGeNiqJL4vc54eW8n... /Users/shildrew/working/monzo-to-qif/lib/qif_creator.rb:52:in `block (2 levels) in create': undefined local variable or method `merchant' for #<QifCreator:0x007f8463308f38> (NameError)
	from /Users/shildrew/working/monzo-to-qif/lib/qif_creator.rb:15:in `each'
	from /Users/shildrew/working/monzo-to-qif/lib/qif_creator.rb:15:in `each_with_index'
	from /Users/shildrew/working/monzo-to-qif/lib/qif_creator.rb:15:in `block in create'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/qif-1.2.0/lib/qif/writer.rb:57:in `initialize'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/qif-1.2.0/lib/qif/writer.rb:23:in `new'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/qif-1.2.0/lib/qif/writer.rb:23:in `block in open'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/qif-1.2.0/lib/qif/writer.rb:22:in `open'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/qif-1.2.0/lib/qif/writer.rb:22:in `open'
	from /Users/shildrew/working/monzo-to-qif/lib/qif_creator.rb:13:in `create'
	from monzo-to-qif.rb:25:in `block (2 levels) in <main>'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/shildrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

Reseting my git checkout to the previous commit on master has allowed me to export a QIF file successfully.

**Comment by KMayne** [comment]
I've submitted a pull request with a fix.
Until that's accepted, there's a working version on my fork https://github.com/KMayne/monzo-to-qif
